apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-registry-proxy
    kubernetes.io/cluster-service: "true"
  name: kube-registry-proxy
  namespace: kube-system
spec:
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    k8s-app: kube-registry-proxy
  type: "NodePort"