apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: kube-registry-proxy
  namespace: kube-system
  name: kube-registry-proxy
spec:
  selector:
    matchLabels:
      name: kube-registry-proxy
  template:
    metadata:
      labels:
        name: kube-registry-proxy
    spec:
      containers:
      - env:
        - name: REGISTRY_HOST
          value: kube-registry.kube-system.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        - name: FORWARD_PORT
          value: "5000"
        image: theobolo/kube-registry-proxy:latest
        imagePullPolicy: Always
        name: kube-registry-proxy
        ports:
        - containerPort: 5000
          hostPort: 5000
          name: registry
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always