kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
token: <<TOKEN>>
tokenTTL: 0
api:
  advertiseAddress: "k8s-dil001.eastus.cloudapp.azure.com,<<IP>>"
  bindPort: "443"
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "true"
  horizontal-pod-autoscaler-sync-period: "10s"
  node-monitor-grace-period: "10s"
apiServerExtraArgs:
  runtime-config: "api/all=true"
