apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeRegistry
  name: kube-registry
spec:
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    k8s-app: kube-registry
  type: ClusterIP
