---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
  namespace: heketi
subsets:
- addresses:
  - ip: 10.0.2.10
  - ip: 10.0.2.100
  - ip: 10.0.2.101
  - ip: 10.0.2.102
  ports:
  - port: 1
    protocol: TCP

---    
apiVersion: v1
kind: Service
metadata:
  name: gluster-endpoints
  namespace: heketi
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  type: ClusterIP
