apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    description: GlusterFS Stateful Set
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"StatefulSet","metadata":{"annotations":{"description":"GlusterFS Stateful Set","tags":"glusterfs"},"generation":1,"labels":{"glusterfs":"deployment"},"name":"glusterfs","namespace":"heketi"},"spec":{"podManagementPolicy":"Parallel","replicas":3,"revisionHistoryLimit":10,"serviceName":"glusterfs","template":{"metadata":{"creationTimestamp":null,"labels":{"glusterfs":"pod","glusterfs-node":"pod"},"name":"glusterfs"},"spec":{"containers":[{"image":"gluster/gluster-centos","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["/bin/bash","-c","systemctl status glusterd.service"]},"failureThreshold":3,"initialDelaySeconds":60,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":3},"name":"glusterfs","readinessProbe":{"exec":{"command":["/bin/bash","-c","systemctl status glusterd.service"]},"failureThreshold":3,"initialDelaySeconds":60,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":3},"resources":{},"securityContext":{"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/heketi","name":"glusterfs-heketi"},{"mountPath":"/run","name":"glusterfs-run"},{"mountPath":"/run/lvm","name":"glusterfs-lvm"},{"mountPath":"/etc/glusterfs","name":"glusterfs-etc"},{"mountPath":"/var/log/glusterfs","name":"glusterfs-logs"},{"mountPath":"/var/lib/glusterd","name":"glusterfs-config"},{"mountPath":"/dev","name":"glusterfs-dev"},{"mountPath":"/sys/fs/cgroup","name":"glusterfs-cgroup"}]}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"nodeSelector":{"storagenode":"glusterfs"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io","operator":"Equal","value":"master"}],"volumes":[{"hostPath":{"path":"/var/lib/heketi","type":""},"name":"glusterfs-heketi"},{"emptyDir":{},"name":"glusterfs-run"},{"hostPath":{"path":"/run/lvm","type":""},"name":"glusterfs-lvm"},{"hostPath":{"path":"/etc/glusterfs","type":""},"name":"glusterfs-etc"},{"hostPath":{"path":"/var/log/glusterfs","type":""},"name":"glusterfs-logs"},{"hostPath":{"path":"/var/lib/glusterd","type":""},"name":"glusterfs-config"},{"hostPath":{"path":"/dev","type":""},"name":"glusterfs-dev"},{"hostPath":{"path":"/sys/fs/cgroup","type":""},"name":"glusterfs-cgroup"}]}},"updateStrategy":{"type":"RollingUpdate"}}}
    tags: glusterfs
  creationTimestamp: null
  generation: 1
  labels:
    glusterfs: deployment
  name: glusterfs
  selfLink: /apis/apps/v1beta1/namespaces/heketi/statefulsets/glusterfs
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      glusterfs: pod
      glusterfs-node: pod
  serviceName: glusterfs
  template:
    metadata:
      creationTimestamp: null
      labels:
        glusterfs: pod
        glusterfs-node: pod
      name: glusterfs
    spec:
      containers:
      - image: gluster/gluster-centos
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - systemctl status glusterd.service
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: glusterfs
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - systemctl status glusterd.service
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/heketi
          name: glusterfs-heketi
        - mountPath: /run
          name: glusterfs-run
        - mountPath: /run/lvm
          name: glusterfs-lvm
        - mountPath: /etc/glusterfs
          name: glusterfs-etc
        - mountPath: /var/log/glusterfs
          name: glusterfs-logs
        - mountPath: /var/lib/glusterd
          name: glusterfs-config
        - mountPath: /dev
          name: glusterfs-dev
        - mountPath: /sys/fs/cgroup
          name: glusterfs-cgroup
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        storagenode: glusterfs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io
        operator: Equal
        value: master
      volumes:
      - hostPath:
          path: /var/lib/heketi
          type: ""
        name: glusterfs-heketi
      - emptyDir: {}
        name: glusterfs-run
      - hostPath:
          path: /run/lvm
          type: ""
        name: glusterfs-lvm
      - hostPath:
          path: /etc/glusterfs
          type: ""
        name: glusterfs-etc
      - hostPath:
          path: /var/log/glusterfs
          type: ""
        name: glusterfs-logs
      - hostPath:
          path: /var/lib/glusterd
          type: ""
        name: glusterfs-config
      - hostPath:
          path: /dev
          type: ""
        name: glusterfs-dev
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: glusterfs-cgroup
  updateStrategy:
    type: RollingUpdate
status:
  replicas: 0
