---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
labels:
  consul: server
name: consul
namespace: kube-system
spec:
podManagementPolicy: OrderedReady
replicas: 3
selector:
  matchLabels:
    consul: server
serviceName: consul
template:
  metadata:
    labels:
      consul: server
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: consul
              operator: In
              values:
              - server
          topologyKey: kubernetes.io/hostname
    containers:
    - args:
      - agent
      - -advertise=$(POD_IP)
      - -bind=0.0.0.0
      - -bootstrap-expect=3
      - -retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local
      - -retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local
      - -retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local
      - -client=0.0.0.0
      - -datacenter=fr
      - -data-dir=/consul/data
      - -domain=cluster.local
      - -server
      - -ui
      - -disable-host-node-id
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      image: consul:0.9.2
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - -c
            - consul leave
      name: consul
      ports:
      - containerPort: 8500
        name: ui-port
        protocol: TCP
      - containerPort: 8400
        name: alt-port
        protocol: TCP
      - containerPort: 53
        name: udp-port
        protocol: TCP
      - containerPort: 8443
        name: https-port
        protocol: TCP
      - containerPort: 8080
        name: http-port
        protocol: TCP
      - containerPort: 8301
        name: serflan
        protocol: TCP
      - containerPort: 8302
        name: serfwan
        protocol: TCP
      - containerPort: 8600
        name: consuldns
        protocol: TCP
      - containerPort: 8300
        name: server
        protocol: TCP
      volumeMounts:
      - mountPath: /etc/ssl/certs
        name: ca-certificates
      - mountPath: /consul/data
        name: consul-data
    dnsPolicy: ClusterFirst
    nodeSelector:
      consul: server
    restartPolicy: Always
    securityContext:
      fsGroup: 1000
    terminationGracePeriodSeconds: 10
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
    volumes:
    - hostPath:
        path: /usr/share/ca-certificates/
        type: ""
      name: ca-certificates
    - hostPath:
        path: /mnt/consul
        type: ""
      name: consul-data
updateStrategy:
  type: RollingUpdate
