---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
      nodePort: 32000
    - protocol: TCP
      port: 443
      name: https
      nodePort: 32001
    - protocol: TCP
      port: 8080
      name: admin
      nodePort: 32002      
  type: NodePort