apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik-ingress-controller
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        #trafiknode: 
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: spec.nodeName
    spec:
      containers:
      - args:
        - -d
        - --logLevel=$(LOGLEVEL)
        - --consul.endpoint=consul.$(NAMESPACE).svc.cluster.local:8500
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LOGLEVEL
          valueFrom:
            configMapKeyRef:
              key: logLevel
              name: traefik
        image: traefik:alpine
        imagePullPolicy: Always
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: admin
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/traefik/traefik.toml
          name: config
          subPath: traefik.toml
        - mountPath: /.htdigest
          name: htdigest
          subPath: .htdigest
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: traefik
        name: config
      - name: htdigest
        secret:
          secretName: htdigest
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
