---
- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Generate bootstrap token
  shell: kubeadm token generate
  register: kube_token_output
  when: admin_st.stat.exists == False

- copy: content="{{ kube_token_output.stdout }}" dest=/tmp/token.txt
  when: admin_st.stat.exists == False

- fetch:
    src: /tmp/token.txt
    dest: roles/node/files/token.txt
    flat: yes
  when: admin_st.stat.exists == False

- copy:
    content: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:{{ apiserver_bind_port }}"
    dest: /tmp/master.txt
  when: admin_st.stat.exists == False

- fetch:
    src: /tmp/master.txt
    dest: roles/node/files/master.txt
    flat: yes
  when: admin_st.stat.exists == False

- name: Init kubernets master
  shell: kubeadm init --apiserver-bind-port {{ apiserver_bind_port }} --token {{ kube_token_output.stdout }}
  when: admin_st.stat.exists == False

- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Create kube home dir
  file:
    path: /home/dil/.kube/
    state: directory

- name: Copy admin.conf to user directory
  shell: cp /etc/kubernetes/admin.conf /home/dil/.kube/config
  when: admin_st.stat.exists == True

- name: Set user of admin.conf
  file: 
    path: /home/dil/.kube/config
    owner: dil
    group: dil
    mode: 0600
  when: admin_st.stat.exists == True

- name: Deploy Weave Net 
  shell: kubectl apply -f https://git.io/weave-kube-1.6 --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy Kubernetes Dashboard 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard-arm.yaml --kubeconfig /etc/kubernetes/admin.conf
