---
- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Set /proc/sys/net/bridge/bridge-nf-call-iptables to 1
  shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  when: admin_st.stat.exists == False

- name: Init kubernets master {{ public_ip }}:{{ apiserver_bind_port }} ({{ k8s_token }})
  shell: kubeadm init --apiserver-bind-port {{ apiserver_bind_port }} --token {{ k8s_token }} --apiserver-cert-extra-sans {{ public_ip }}
  when: admin_st.stat.exists == False

- name: Wait 300 seconds for kubernetes api server
  wait_for:
    port: 443

- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Create kube home dir
  file:
    path: /home/dil/.kube/
    state: directory

#- name: Create root kube home dir
#  file:
#    path: /root/.kube/
#    state: directory

- name: Copy admin.conf to user directory
  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/home/dil/.kube/config

#- name: Copy admin.conf to root directory
#  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/root/.kube/config

- name: Set user of admin.conf
  file: 
    path: /home/dil/.kube/config
    owner: dil
    group: dil
    mode: 0600
  when: admin_st.stat.exists == True

- name: Deploy weave net 
  shell: "{{kubectl}} apply -f https://cloud.weave.works/k8s/v1.8/net.yaml"

- name: Deploy kubernetes dashboard 
  shell: "{{kubectl}} apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml "

- name: Deploy kubernetes dashboard admin RBAC 
  shell: "{{kubectl}} apply -f roles/master/files/kube-dashboard-admin.yaml "

- name: Deploy heapster 
  shell: "{{kubectl}} apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/standalone/heapster-controller.yaml"
  
- name: Deploy heapster RBAC 
  shell: "{{kubectl}} apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml "
