---
- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Init kubernets master {{ public_ip }}:{{ apiserver_bind_port }} ({{ k8s_token }})
  shell: kubeadm init --apiserver-bind-port {{ apiserver_bind_port }} --token {{ k8s_token }} --apiserver-cert-extra-sans {{ public_ip }}
  when: admin_st.stat.exists == False

- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Create kube home dir
  file:
    path: /home/dil/.kube/
    state: directory

- name: Copy admin.conf to user directory
  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/home/dil/.kube/config

- name: Set user of admin.conf
  file: 
    path: /home/dil/.kube/config
    owner: dil
    group: dil
    mode: 0600
  when: admin_st.stat.exists == True

- name: Deploy weave net 
  shell: kubectl apply -f https://git.io/weave-kube-1.6 --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy kubernetes dashboard 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy kubernetes dashboard admin RBAC 
  shell: kubectl apply -f roles/master/files/kube-dashboard-admin.yaml --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy heapster 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/standalone/heapster-controller.yaml --kubeconfig /etc/kubernetes/admin.conf
  
- name: Deploy heapster RBAC 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml --kubeconfig /etc/kubernetes/admin.conf

- name: Create namespace heketi 
  shell: kubectl create ns heketi --kubeconfig /etc/kubernetes/admin.conf > /dev/null 2>&1
  ignore_errors: yes
  register: ns_out
  changed_when: ns_out.rc == 0
  failed_when: false

- name: Creates gluster bricks directory
  file: path=/bricks state=directory

- name: Deploy glusterfs stateful set 
  shell: kubectl apply -f roles/master/files/glusterfs-statefulset.yaml --kubeconfig /etc/kubernetes/admin.conf
  
- name: Label glusterfs nodes
  shell: kubectl label node --all storagenode=glusterfs > /dev/null 2>&1
  ignore_errors: yes
  register: label_out
  changed_when: label_out.rc == 0
  failed_when: false
