---
- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Init kubernets master ({{ k8s_token }})
  shell: kubeadm init --apiserver-bind-port {{ apiserver_bind_port }} --token {{ k8s_token }}
  when: admin_st.stat.exists == False

- stat: path=/etc/kubernetes/admin.conf
  register: admin_st

- name: Create kube home dir
  file:
    path: /home/dil/.kube/
    state: directory

- name: Copy admin.conf to user directory
  shell: cp /etc/kubernetes/admin.conf /home/dil/.kube/config
  when: admin_st.stat.exists == True

- name: Set user of admin.conf
  file: 
    path: /home/dil/.kube/config
    owner: dil
    group: dil
    mode: 0600
  when: admin_st.stat.exists == True

- name: Deploy weave net 
  shell: kubectl apply -f https://git.io/weave-kube-1.6 --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy kubernetes dashboard 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy kubernetes dashboard admin RBAC 
  shell: kubectl apply -f kube-dashboard-admin.yaml --kubeconfig /etc/kubernetes/admin.conf

- name: Deploy heapster 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/standalone/heapster-controller.yaml --kubeconfig /etc/kubernetes/admin.conf
  
- name: Deploy heapster RBAC 
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml --kubeconfig /etc/kubernetes/admin.conf

- name: Create namespace heketi 
  shell: kubectl create ns heketi --kubeconfig /etc/kubernetes/admin.conf > /dev/null 2>&1
  ignore_errors: yes

- name: Deploy glusterfs stateful set 
  shell: kubectl apply -f glusterfs-statefulset.yaml --kubeconfig /etc/kubernetes/admin.conf
  
