---
# tasks file for traefik
- name: Label consul nodes
  shell: kubectl label --overwrite nodes node0 node1 node2 consul=server

- name: Deploy consul nodes
  shell: kubectl apply -f roles/traefik/files/consul-statefulset.yaml

- name: 'Wait for consul-0'
  shell: kubectl get pod consul-0 -n kube-system >/dev/null 2>&1
  register: consul_result
  until: consul_result.rc == 0
  retries: 100
  delay: 5

- name: Get kube dns ip address
  shell: kubectl get svc kube-dns -n kube-system | tail -n1 | awk '{ print $3 }'
  register: dns_out

- name: Deploy resolv.conf config map
  shell: cat roles/traefik/files/dns-cm.yaml | sed "s#nameserver .*#nameserver {{ dns_out.stdout }}#" | kubectl apply -f -    
   
- name: Deploy traefik config map
  shell: kubectl apply -f roles/traefik/files/traefik-cm.yaml
    
- name: Deploy traefik service account
  shell: kubectl apply -f roles/traefik/files/traefik-sa.yaml

- name: Deploy traefik service
  shell: kubectl apply -f roles/traefik/files/traefik-svc.yaml

- name: Deploy traefik deamonset
  shell: kubectl apply -f roles/traefik/files/traefik-ds.yaml

- name: Wait for first traefik controller
  wait_for:
    port: 32002

- name: Get pod name of a traefik controller
  shell: kubectl get pods -n kube-system | grep traefik-ingress-controller | grep Running | tail -n1 | awk '{ print $1 }'
  register: pod_name_out

- name: Check if config exits
  shell: kubectl --namespace kube-system exec -it consul-0 consul kv get traefik/loglevel
  register: config_out
  changed_when: config_out.stdout.find('Error!') != -1

- name: Get pod name of a traefik controller
  shell: kubectl get pods -n kube-system | grep traefik-ingress-controller | grep Running | tail -n1 | awk '{ print $1 }'
  register: pod_name_out
  when: config_out.changed

- name: Copy config to consul
  shell: kubectl --namespace kube-system exec -it {{ pod_name_out.stdout }} traefik storeconfig
  when: config_out.changed

- name: Bugfix https://github.com/containous/traefik/issues/927
  shell: kubectl --namespace kube-system exec -it consul-0 consul kv delete traefik/acme/storagefile  
  when: config_out.changed
